project_id = "lchmzbfwnjtzaeenfqql"

[functions.fetch-news]
verify_jwt = false

[functions.summarize-article]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false